### ISSUE TITLE
Image not working on Raspberry pi Zero 2 W

### ISSUE THREAD

**Issue by greppp** [pirateradiohack/PiRadio#11]
Downloaded an image from here : https://github.com/pirateradiohack/Transistor/releases/tag/2022-04-10-Fix_Podcasts_Update-SSH

Burned it with Raspberry Pi Imager V1.7.3 on Linux

Started the Raspberry Pi Zero 2 W

Gets stuck during boot on this screen :

![signal-2022-12-26-195016_002](https://user-images.githubusercontent.com/15223909/209593293-a0a27145-fe36-4ca8-bb9e-5630c64ad57d.jpeg)

**Comment by pirateradiohack** [comment]
I am working on a new version. It is currently running on my Raspberry Pi Zero 2 W.  
I will publish it soon.

**Comment by greppp** [comment]
Amazing news! Thank you!

**Comment by pirateradiohack** [comment]
The new version of the project that works on the Raspberry Pi Zero W version 2 can be found here : https://github.com/pirateradiohack/Transistor

The first release is there : https://github.com/pirateradiohack/Transistor/releases/tag/2.0.0-beta

As the tag implies, it is a beta release. You can see the detail of what works on the release page.

I am writing issues there in order to get to feature parity with the first version of the project.
